server {
    listen 80;
    server_name moran-porto.my.id;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name grafana.moran-porto.my.id;

    location / {
        proxy_pass http://grafana:3000;
    }
}

server {
    listen 80;
    server_name prometheus.moran-porto.my.id;

    location / {
        proxy_pass http://prometheus:9090;
    }
}
