events {
  worker_connections 1024;
}

http {

  upstream api {
    server api:3000;
  }

  upstream grafana {
    server grafana:3000;
  }

  server {
    listen 80;

    # App utama
    location / {
      proxy_pass http://api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Grafana via /grafana
    location /grafana/ {
      proxy_pass http://grafana/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
